### ISSUE TITLE
Support python 3 (if possible)

### ISSUE THREAD

**Issue by itziakos** [enthought/traits-enaml#77]

**Comment by jwiggins** [comment]
nucleic/atom#65 has been open for almost a year now...

**Comment by jwiggins** [comment]
nucleic/enaml#117 is also directly relevant

**Comment by bburan** [comment]
Now using traits-enaml + enaml + atom with Python 3 using Matthieu's hard work on porting enaml + atom.

**Comment by MatthieuDartiailh** [comment]
I now have write access on nucleic repos so things should move forward on enaml side.

**Comment by jwiggins** [comment]
That's excellent news @MatthieuDartiailh! I'm looking forward to using enaml with Python 3 :smiley:

**Comment by MatthieuDartiailh** [comment]
Python 3 support is in master ! In about a week Qt5 support should land and I will try to do a release shortly after.

**Comment by MatthieuDartiailh** [comment]
Enaml 0.10.1 now supports Python 3 and Qt5. Should appear soon on conda-forge and on PyPI (as soon as @sccolbert gives me access to it)

**Comment by MatthieuDartiailh** [comment]
enaml 0.10.2 which fixes a number of bugs is available both on conda-forge and on PyPI in case you are still interested.
